export enum MetadataKey {
  CONTROLLER = 'CONTROLLER',
  GENERICS = 'GENERICS',
  MIDDLEWARES = 'MIDDLEWARES',
  ROUTE = 'ROUTE',
  PARAM = 'PARAM',
  RESULT = 'RESULT',
  ERROR = 'ERROR',
  MODEL = 'MODEL',
  PROP = 'PROP',
  COLLECTION = 'COLLECTION',
  FIELD = 'FIELD',
  EMBEDDED = 'EMBEDDED',
  INDEX = 'INDEX',
  VALIDATOR = 'VALIDATOR',
  HOOK = 'HOOK'
}

export default MetadataKey
