export enum MetadataKey {
  CONTROLLER = 'CONTROLLER',
  GENERICS = 'GENERICS',
  MIDDLEWARE = 'MIDDLEWARE',
  ROUTE = 'ROUTE',
  PARAM = 'PARAM',
  RESPONSE = 'RESPONSE',
  ERROR = 'ERROR',
  PROP = 'PROP',
  COLLECTION = 'COLLECTION',
  FIELD = 'FIELD',
  EMBEDDED = 'EMBEDDED',
  INDEX = 'INDEX',
  VALIDATOR = 'VALIDATOR',
  HOOK = 'HOOK',
  SCHEMA = 'SCHEMA',
  MODEL = 'MODEL'
}

export default MetadataKey
